### ISSUE TITLE
Bug: Entering valid Broker information and clicking Update Broker gives OK message

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#212]
![image](https://user-images.githubusercontent.com/5267251/102389692-7955ba00-3ff9-11eb-9ea0-91f4a4cb0f13.png)

attached logs

[tradebull.log](https://github.com/anmoldeep0123/kite-webapp/files/5704699/tradebull.log)

**Comment by theheapdump** [comment]
Did you give First Name as 1 character ?? 

**java.lang.StringIndexOutOfBoundsException: begin 0, end 2, length 1**
	at java.lang.String.checkBoundsBeginEnd(String.java:3319) ~[?:?]
	at java.lang.String.substring(String.java:1874) ~[?:?]
	at org.kiteandee.service.bizlogic.user.UserServiceImpl.setCustomerReferralCode(UserServiceImpl.java:364) ~[classes!/:1.0]

**Comment by theheapdump** [comment]
i will add first name validations to be atleast 3 characters !!! @bevanamit

**Comment by theheapdump** [comment]
please retest and close @bevanamit
